postgres:
  image:
    repository: postgres
    tag: "15-alpine"
  db: app_db
  user: app_user
  password: app_password
  storage: 1Gi
  storageClassName: gp2

backend:
  image:
    repository: ghcr.io/cablo/books-be
    tag: sha-647a7ba
  replicas: 1
  port: 8080
  servicePort: 8001
  datasource:
    url: "jdbc:postgresql://postgres-service:5432/app_db"
    username: app_user
    password: app_password

frontend:
  image:
    repository: ghcr.io/cablo/books-fe
    tag: sha-539fb7a
  replicas: 1
  port: 80
  servicePort: 8000

ingress:
  className: nginx
  backendPath: /api(/|$)(.*)
  frontendPath: /