apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}